---
- name: NEW Playbook to Enable Secure HTTPS CipherSuites
  hosts: iosxe
  connection: netconf
  gather_facts: false

  vars_files:
   - ~/clemea2024-devwks-2008/vaults/ciscolive.vault

  tasks:
    - name: secure-https
      netconf_get:
        filter: |
            <filter xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
                <ip>
                  <http xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-http">
                    <secure-ciphersuite>
                      <dhe-aes-gcm-sha2/>
                      <ecdhe-ecdsa-aes-gcm-sha2/>
                      <ecdhe-rsa-aes-cbc-sha2/>
                      <tls13-aes128-gcm-sha256/>
                      <tls13-aes256-gcm-sha384/>
                      <tls13-chacha20-poly1305-sha256/>
                    </secure-ciphersuite>
                  </http>
                </ip>
              </native>
            </filter>

